### ISSUE TITLE
[BUG] ClientConfig functionality does not seem to work

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#14]
## Description [(i)](## "A (short) description as to what the issue is.")

In the ClientConfig utility I've tried adding logo's or updating colors, but after saving nothing seems to change.

## Reproduction  [(i)](## "Step by step reproduction instructions for the bug or a clear indication of where what went wrong exactly if it cannot be reproduced.")

1. Click 'Configuration' icon (wrench) in the Main menu
2. Click tab Presentation
3. Select image for logo's and badges 
4. Select primary and secondary theme colors
5. Click button Save configuration
6. Preview website
7. Notice that nothing has changed

## Related exceptions, screenshots, etc. [(i)](## "(Links to) exceptions, including the actual exception text or descriptions of the errors as _specific_ as possible and if relevant screenshots or videos of the issue. In general anything that is 'proof' of the issue.")
- No exceptions or messages

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- ModMore > [ClientConfig](https://docs.modmore.com/en/Open_Source/ClientConfig/index.html)

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

<img width="818" alt="rb-14-exisiting-ClientConfig" src="https://github.com/user-attachments/assets/48f004ba-c036-490b-b1ae-dc7fbd55c503">

## Acceptance criteria / TODO [(i)](## "The (key) elements that when completed / fulfilled complete this issue.")
- Ensure ClientConfig settings are saved to database
- Ensure CSS / JS rebuild is initiated

## Additional information [(i)](## "Suggestions for technical implementation, solution pointers, information that provides extra context or background information, related issues, comments, etc.")
- Perhaps something to do with the [ClientConfig_ConfigChange](https://docs.modmore.com/en/Open_Source/ClientConfig/ConfigChange_Event.html) Event not being fired properly to rebuild the Fomantic site.css?
- Is there a possibility to display any feedback on whether the CSS / JS has successfully been rebuilt or has failed to rebuild?

## TODO  [(i)](## "Checklist to ensure critical reviews of specification are done by issue creator and lead developer before actual development starts.")
- [x] Self review of issue specification
- [x] Lead dev review of issue specification

**Comment by hugopeek** [comment]
Apologies, it needed a fresh `npm install` in root, and the `romanesco.env_path` setting was incorrect. This setting contains the $PATH setting of the local Linux user. Because the PHP process is also owned by this user, PHP will have access to the same commands (Gitify, NPM) through the local $PATH.

In addition:

- A gulp build process is launched in the background any time you save any styling related settings under ClientConfig. Feedback is logged to core/cache/logs/css.log, and you'll also notice that the ClientConfig CMP is greyed out during this process. It should take around 10-15 seconds to complete.
- This functionality utilizes Symfony Process to securely launch system processes (instead of simply using exec in PHP, which comes with security risks).
- At some point, we could move this 'Update CSS' task to a separate CMP, for managing / launching other kinds of NodeJS or deployment processes too. I'm working on a stand-alone package for this.

**Comment by hugopeek** [comment]
@martenwilmink I also added an extra to quickly open the error log from the top-right corner:
![image](https://github.com/user-attachments/assets/bf816e94-e09f-4070-8752-3433a77221d3)

This allows you to view the CSS log also, but there is no output still on first try. Probably the formatting of that log file is different from the default MODX error log.
